ai: ai.cc
	g++ -o ai -O2 ai.cc
noop: noop.cc
	g++ -o noop -O2 noop.cc
disallowed: disallowed.cc
	g++ -o disallowed -O2 disallowed.cc
skeleton: skeleton.cc
	g++ -o skeleton -O2 skeleton.cc
bad-cpu: bad-cpu.cc
	g++ -o bad-cpu bad-cpu.cc
bad-mem: bad-mem.cc
	g++ -o bad-mem bad-mem.cc
bad-syscall: bad-syscall.cc
	g++ -o bad-syscall bad-syscall.cc
bad-walltime: bad-walltime.cc
	g++ -o bad-walltime bad-walltime.cc
almost-exceeding-cpu: almost-exceeding-cpu.cc
	g++ -o almost-exceeding-cpu almost-exceeding-cpu.cc
almost-not-exceeding-cpu: almost-not-exceeding-cpu.cc
	g++ -o almost-not-exceeding-cpu almost-not-exceeding-cpu.cc